[package]
name = "cod"
version = "4.1.1"
edition = "2021"

description = "A mini terminal drawing utility."
authors = ["Kyllingene"]
license = "MIT"

repository = "https://github.com/Kyllingene/cod"
homepage = "https://github.com/Kyllingene/cod"

categories = ["command-line-interface"]
keywords = ["tui", "terminal", "command-line"]

[dependencies]
console = { git = "https://github.com/console-rs/console", rev = "572e9a5f24b1142338d8133bc571b22093339f72", optional = true }

[lib]
name = "cod"
path = "src/lib.rs"

[features]
input = ["dep:console"]
