[package]
name = "cod"
version = "2.0.0"
edition = "2021"

description = "A mini terminal drawing utility."
authors = ["Kyllingene"]
license = "MIT"

repository = "https://github.com/Kyllingene/cod"
homepage = "https://github.com/Kyllingene/cod"

categories = ["command-line-interface"]
keywords = ["tui", "terminal", "command-line"]

[dependencies]
device_query = "1.1.1"

[lib]
name = "cod" 
path = "src/lib.rs"
